---
title: "Python and RStudio"
author: "Dan Maxwell"
date: "August 9, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)
```

## Python and RMarkdown

RStudio documentation indicates that you can use the Python engine in a code snippet by referencing the interpreter like this: {python}.  However, this only works if python.exe is in the Windows PATH variable.  In the case of most Anaconda installations, the path to the python.exe is c:/ProgramData/Anaconda3.  Add this to the path variable by first clicking the Windows Start button and then right-click Computer and click Properties.  The Control Panel Home window now opens.  Click Advanced system settings and then the Environment Variables button.  And finally, select PATH and click the Edit button.

See also: [Python Plots in RMarkdown](https://stackoverflow.com/questions/50352614/r-markdown-how-can-i-make-rstudio-display-python-plots-inline-instead-of-in-new).

The following chunk embeds Python code that creates a graph which is subsequently output to a document as a result of the knit process.

```{python, results='asis'}
import pandas as pd
import matplotlib.pyplot as plt
import os

os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] =  'c:/ProgramData/Anaconda3/Library/plugins/platforms'

df  = pd.read_csv('c:/informatics/gapminder.csv', index_col = 0)

ax = plt.axes()
ax.set(xlabel = 'Year', 
       ylabel = 'Years', 
         xlim = (1950, 2010), 
        title = 'Life Expectancy')

#
# Subset by country and plot.
#

df_gap = df.loc['United States']
plt.plot(df_gap[['year']], df_gap[['lifeExp']], color = 'blue')
plt.show()

```


